name: Push Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Run automated end-to-end tests
      run: npm run e2e

    # - name: Run zip_extension.sh
    #   run: sh scripts/zip_extension.sh

    - name: Get extension version from manifest
      id: get_version
      run: echo "VERSION=$(jq -r .version manifest.json)" >> $GITHUB_OUTPUT

    - name: Upload project zip folder
      uses: actions/upload-artifact@v4
      with:
        name: wikipedia_time_travel_${{steps.get_version.outputs.VERSION}}
        path: | 
          manifest.json
          background.js 
          popup/ 
          icons/ 
