name: Push Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Run zip_extension.sh
      run: sh scripts/zip_extension.sh

    - name: Upload project zip file
      uses: actions/upload-artifact@v2
      with:
        name: wikipedia_time_travel
        path: wikipedia_time_travel_*.zip
